### ISSUE TITLE
Plastid 0.4.7 completing installation but not importable on OSX

### ISSUE THREAD

**Issue by joshuagryphon** [joshuagryphon/plastid#13]
Two users have reported that Plastid passes installation, but fails during runtime on OSX. This appears to be conda-independent, and occurs even when installing inside `virtualenv`. After a successful install, `import plastid` yields:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/env/lib/python2.7/site-packages/plastid/__init__.py", line 40, in <module>
    from plastid.genomics.roitools import (GenomicSegment,
ImportError: dlopen(/Users/username/env/lib/python2.7/site-packages/plastid/genomics/roitools.so, 2): Library not loaded: @rpath/pysam/libctabixproxies.so
  Referenced from: /Users/username/env/lib/python2.7/site-packages/plastid/genomics/roitools.so
  Reason: image not found
```

Collecting more information

**Comment by joshuagryphon** [comment]
Looking into this a bit, it seems like `clang` is making dynamically-linked libraries, which is weird because on Linux GCC makes static libs for all of Plastid's extensions.

**Comment by joshuagryphon** [comment]
Fixed by removing `EXTRA_LINK_ARGS` from setup.py. See commit 340e6c6f1ef87823eddddd5184d6991926ae2bcf
