### ISSUE TITLE
KeyError: 'zero_point' when running metagene count

### ISSUE THREAD

**Issue by JPMARKS** [joshuagryphon/plastid#26]
Dear Plastid Team,

I am working through the tutorial for the metagene analysis and have come up with an error that neither me or our IT department was able to solve. The metatgene_generate command runs successfully and I generated ROI files. However, the metagene count command generates the following error. I would appreciate any assistance or guidance in solving this problem.

-James

metagene [2018-07-09 18:29:33]: Opening ROI file merlin_cds_start_rois.txt ...
Traceback (most recent call last):
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3064, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'zero_point'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/apps/plastid/0.4.8/bin/metagene", line 11, in <module>
    load_entry_point('plastid==0.4.8', 'console_scripts', 'metagene')()
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/plastid/bin/metagene.py", line 1188, in main
    do_count(args,al,pp,printer)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/plastid/bin/metagene.py", line 821, in do_count
    norm_start, norm_end = _get_norm_region(roi_table, args)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/plastid/bin/metagene.py", line 744, in _get_norm_region
    flank_upstream = roi_table["zero_point"][0]
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/generic.py", line 2486, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/local/Anaconda/envs_app/plastid/0.4.8/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3066, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'zero_point'

**Comment by joshuagryphon** [comment]
Hi @JPMARKS ,

Thank you for the detailed stack trace! I'll take a look to see if I can replicate this error. When you have a moment, could you let me know which version of `pandas` is installed in your environment?

Thanks & best,
Josh

**Comment by joshuagryphon** [comment]
Interesting. The lines you pasted are correct; though they're not the first 10 in my file (which starts with `ORFL100C` as the first entry).

When I ran the demo, I found one runtime error but otherwise everything completed normally. I'm using the following versions in my Python 3.5 environment:

```
Package         Version
--------------- -------
biopython       1.66   
cycler          0.10.0 
Cython          0.23.4 
matplotlib      1.5.1  
numpy           1.10.4 
pandas          0.20.1 
pip             10.0.1 
plastid         0.4.8  
pyparsing       2.1.0  
pysam           0.9.0  
python-dateutil 2.5.0  
pytz            2015.7 
scipy           0.17.0 
setuptools      20.2.2 
six             1.10.0 
termcolor       1.1.0  
twobitreader    3.1.0  
wheel           0.29.0 
```

Could you reply with a paste of the output of `pip freeze`, run inside your Anaconda environment? I'm wondering if I can elicit the error by reproducing your environment as closely as possible. Please note, I don't have much experience with Anaconda but it has caused strange behaviors in the past.

**Comment by joshuagryphon** [comment]
or, this could be caused by having a truncated file. Your `merlin_cds_start_rois.txt` should have 538 lines total, and the first 10 should look like this:

```## date = '2018-07-12 21:27:57.319251'
## execstr = '/home/joshua/venv/sandbox35/bin/metagene generate merlin_cds_start --landmark cds_start --annotation_files merlin_orfs.gtf --downstream 200'
## args = {  
##          'add_three'                 : False,,
##          'annotation_files'          : ['merlin_orfs.gtf'],,
##          'annotation_format'         : 'GTF2',,
##          'bed_extra_columns'         : 0,,
##          'downstream'                : 200,,
##          'gff_cds_types'             : {'CDS_fragment', 'CDS', 'CDS_indpendently_known', 'CDS_predicted'},,
##          'gff_exon_types'            : {'exon_of_single_exon_gene', 'pseudogenic_exon', 'five_prime_coding_exon', 'exon', 'three_prime_coding_exonfive_prime_noncoding_exon', 'three_prime_noncoding_exon', 'interior_exon', 'coding_exon', 'noncoding_exon', 'interior_coding_exon'},,
```

How many lines is your copy of `merlin_cds_start_rois.txt`? You can find out by entering a terminal and typing `wc -l merlin_cds_start_rois.txt`

**Comment by JPMARKS** [comment]
Hi Josh,

I definitely have a truncated file. Only 413 lines. 

```
## execstr = '/usr/local/apps/plastid/0.4.8/bin/metagene generate merlin_cds_start --landmark cds_start --annotation_files merlin_orfs.gtf --downstream 200'
## args = {  
##          'add_three'                 : False,,
##          'annotation_files'          : ['merlin_orfs.gtf'],,
##          'annotation_format'         : 'GTF2',,
##          'bed_extra_columns'         : 0,,
##          'downstream'                : 200,,
##          'gff_cds_types'             : {'CDS_indpendently_known', 'CDS', 'CDS_fragment', 'CDS_predicted'},,
##          'gff_exon_types'            : {'noncoding_exon', 'coding_exon', 'interior_coding_exon', 'three_prime_noncoding_exon', 'interior_exon', 'exon_of_single_exon_gene', 'five_prime_coding_exon', 'three_prime_coding_exonfive_prime_noncoding_exon', 'pseudogenic_exon', 'exon'},,
```

As for my modules currently installed, it's an extremely long list. I'm running this on a large group server with many modules installed. I am going to set up an environment on my laptop with only the essential modules and attempt to rerun it.

**Comment by joshuagryphon** [comment]
In that case, please also try just re-running the `generate` command in your current environment (group server) and seeing if you end up with a 538 line file. My suspicion is that this is a random hiccup with file i/o (messed up disk write, or something like that) rather than a bug.

If the error is repeatable, and the re-run generates a truncated file, I'll be very confused.

**Comment by JPMARKS** [comment]
Hi Josh,

I just wanted to let you know that I was able to get Plastid to work on a local install with an environment that only contains the suggested packages and versions. I was successful in replicating the error on our server though.

-James

**Comment by joshuagryphon** [comment]
Hi James,

Thank you for the update. I'm glad you got things working. Please let me know if this pops up again!

Best,
Josh
