### ISSUE TITLE
Undefined symbol caused by compilation error only under Python 2.7.17 (3.x, 2.7.15 are ok)

### ISSUE THREAD

**Issue by joshuagryphon** [joshuagryphon/plastid#41]
## Phenomenon

Build is silently failing on recently upgraded versions of Ubuntu 18.04, in the sense that build completes, but importing `plastid.genomics.map_factories` results in an `undefined symbol`:

```python
>>> from plastid import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plastid/__init__.py", line 45, in <module>
    from plastid.genomics.genome_array import (
  File "plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
ImportError: plastid/genomics/map_factories.so: undefined symbol: bgzf_read
```

## Terms

* computer A: Running Ubuntu 18.04, but has not experienced a `sudo apt-get upgrade` in a long time
* computer B: Running Ubuntu 18.04, upgraded weekly

## Notes
`undefined symbol` smells of an issue with one or more of: the C compiler, header files, or source code. However:

* the `plastid` source code hasn't changed
* the relevant header files, which do come from `pysam` have changed across versions of `pysam`, but:
    * all versions of pysam (including latest) work on computer A
    * no version of pysam (including that in `requirements.txt`) works on computer B

This points to the C compiler or something close to it 

### GCC

This can't be the whole picture:

* Computer A is running GCC 7.4.0. Computer B is running 7.5.0
* Downgrading to GCC 7.4.0 on Computer B did not solve the problem
* Upgrading to GCC 8.0.0 on Computer B also did not solve the problem
* Build succeeds & all tests pass in a Docker container of Ubuntu 16.04 running GCC 4.x.x or similar

### Python packages

These tests have been done in `virtualenvs` as well as Docker containers:

* the error is not a function of Python dependencies, whether `imported` or `cimported` (working versions of all dependencies from computer A, when installed on computer B, triggered same error)
* this is not a function of Python build chain (versions of `setuptools`, `pip`, and `Cython` more up-to-date on computer A than on computer B. Upgrading on computer B to versions on computer A did not solve problem)
* Install succeeds on computer A in an Ubuntu 16.04 Docker container with the latest versions of everything in PyPI and the Ubuntu 16.04 repositories
* Install fails on computer A in an Ubuntu 18.04 Docker container with the latest versions of everything in PyPI and the Ubuntu 16.04 repositories

**Comment by joshuagryphon** [comment]
## Potential connection to Python versions

* Tests pass under Python 3.6.9, 3.7, and 3.8 on both machines:

    *  in an upgraded Ubuntu 18.04 Docker container while the error occurs under Python 2.7.17 (container running on computer A, set up to mimic computer B)
    * on computer B in a `virtualenv`
    * on computer A outside `virtualenv` and docker containers

* Tests pass under Python 2.7 only on computer A
   * Computer A is running Python 2.7.15
   * Computer B, and upgraded 18.04 Docker container on computer A are both running Python 2.7.17

**Comment by joshuagryphon** [comment]
Since Python 2.7 is EOLed anyway, I won't fix this.

**Comment by joshuagryphon** [comment]
Python 2.x support is now officially dropped.
