### ISSUE TITLE
ModuleNotFoundError: No module named 'plastid.genomics.roitools'

### ISSUE THREAD

**Issue by pkerpedjiev** [joshuagryphon/plastid#42]
Hey, I wanted  to try out plastid but got the following error:

```
>>> import plastid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pkerpedjiev/miniconda3/envs/cenv4/lib/python3.8/site-packages/plastid/__init__.py", line 39, in <module>
    from plastid.genomics.roitools import (
ModuleNotFoundError: No module named 'plastid.genomics.roitools'
```

Any suggestions? I'm in a conda environment, Python 3.8 and installed plastid using `pip install plastid`.

**Comment by mjim18** [comment]
I have a similar issue. I installed plastid locally using `python -m pip install plastid --user`. My error is the same as @pkerpedjiev. I think it's an error with the PATH. I can see that it was installed when I use `pip list`.

**Comment by EricDeveaud** [comment]
same problem here with a `pip install plastid` in a virtualenv

solved with the following command given in the documentation: see https://plastid.readthedocs.io/en/latest/installation.html

`pip install --verbose  --no-cache-dir --install-option="--recythonize" plastid`

Eric

**Comment by joshuagryphon** [comment]
Hi folks,
Sorry about that! Looking into this now. @EricDeveaud thank you for providing the workaround and the clue. My suspicion is that an upstream change in `pip` is causing the `build_ext` to longer trigger before `install`

**Comment by Eduardo-vsouza** [comment]
Hi, any updates on that bug? I'm still unable to install it properly using pip.

**Comment by pkerpedjiev** [comment]
Lol. I don't even remember what I wanted to use plastid for. But better late than never. Thanks!
