### ISSUE TITLE
Error when converting GFF3 to GTF2

### ISSUE THREAD

**Issue by ale07alvarez** [joshuagryphon/plastid#44]
`reformat_transcripts --annotation_files Drosophila_melanogaster.BDGP6.28.100.sorted.gff3 --annotation_format GFF3 --sorted --output_format GTF2 Drosophila_melanogaster.BDGP6.28.100.sorted.gtf2
`
Traceback (most recent call last):
  File "###/opt/anaconda3/envs/plastid/bin/reformat_transcripts", line 11, in <module>
    load_entry_point('plastid==0.4.7', 'console_scripts', 'reformat_transcripts')()
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/plastid/__init__.py", line 44, in <module>
    from plastid.genomics.genome_array import (BAMGenomeArray,
  File "###/opt/anaconda3/envs/plastid/lib/python3.6/site-packages/plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
  File "libchtslib.pxd", line 2530, in init plastid.genomics.map_factories (/anaconda/conda-bld/plastid_1494346258083/work/plastid-0.4.7/plastid/genomics/map_factories.c:26281)
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80

**Comment by AmmarDharani** [comment]
Hi @ale07alvarez, 

I was experiencing the same error. The way I fixed it was switching my environment to Python 2.7 instead of Python 3.6. The error disappeared and I could use Plastid fine afterwards. If you're using Anaconda, make a new environment with Python v. 2.7: `conda create --name py2 plastid python=2.7` and then once you activate the new environment `conda activate py2`, the error will go away.

**Comment by joshuagryphon** [comment]
Hi folks-
It's two years later. Is this still relevant?

**Comment by bribibel** [comment]
Thank you @AmmarDharani! I was having a problem trying to run metagene from a conda-downloaded version, getting (I think) similar errors and a Bio.Alphabet error, but I installed using your method and it seems to be running. Thank you!
