### ISSUE TITLE
Building wheel is failing in local install

### ISSUE THREAD

**Issue by BeastyBlacksmith** [joshuagryphon/plastid#57]
I am trying to install this package locally from source using any of

```python
pip install --user .
pip install --user -e .
pip install --user --global-option="--recythonize" .  # since --install-option was removed by pip
```
but I always get the following error
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy>=0.15.1 (from plastid==0.6.1)
  Using cached scipy-1.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
Collecting pandas>=0.17.0 (from plastid==0.6.1)
  Using cached pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
Requirement already satisfied: matplotlib>=1.4.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (3.7.2)
Collecting biopython>=1.64 (from plastid==0.6.1)
  Using cached biopython-1.81-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting twobitreader>=3.0.0 (from plastid==0.6.1)
  Using cached twobitreader-3.1.7-py3-none-any.whl
Collecting termcolor (from plastid==0.6.1)
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: numpy>=1.9.4 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (1.23.5)
Requirement already satisfied: pysam>=0.8.4 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (0.21.0)
Requirement already satisfied: cython>=0.22.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (3.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (9.5.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from pandas>=0.17.0->plastid==0.6.1) (2023.3)
Collecting tzdata>=2022.1 (from pandas>=0.17.0->plastid==0.6.1)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: six>=1.5 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->plastid==0.6.1) (1.16.0)
Building wheels for collected packages: plastid
  Building wheel for plastid (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for plastid (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying plastid/genomics/roitools.pyx -> build/lib.linux-x86_64-cpython-310/plastid/genomics
      copying plastid/genomics/map_factories.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
      copying plastid/genomics/roitools.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
      copying plastid/genomics/c_common.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
      copying plastid/readers/bigwig.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
      copying plastid/readers/bbifile.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
      copying plastid/readers/bigbed.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
      running build_ext
      building 'plastid.genomics.c_common' extension
      gcc -pthread -B /home/moritzloewer/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/moritzloewer/anaconda3/include -fPIC -O2 -isystem /home/moritzloewer/anaconda3/include -fPIC -I/home/moritzloewer/Bachelor/plastid/plastid/kent/src/htslib -I/home/moritzloewer/Bachelor/plastid/plastid/kent/src/inc -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/numpy/core/include -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam/include/htslib -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam/include/samtools -I/home/moritzloewer/anaconda3/include/python3.10 -c /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.c -o build/temp.linux-x86_64-cpython-310/home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.o
      gcc -pthread -B /home/moritzloewer/anaconda3/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/moritzloewer/anaconda3/lib -Wl,-rpath-link,/home/moritzloewer/anaconda3/lib -L/home/moritzloewer/anaconda3/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/moritzloewer/anaconda3/lib -Wl,-rpath-link,/home/moritzloewer/anaconda3/lib -L/home/moritzloewer/anaconda3/lib build/temp.linux-x86_64-cpython-310/home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.o -lssl -lcrypto -lz -o build/lib.linux-x86_64-cpython-310/plastid/genomics/c_common.cpython-310-x86_64-linux-gnu.so
      warning: plastid/genomics/map_factories.pyx:134:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: plastid/genomics/map_factories.pyx:145:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      LONG   = np.long
      
      ctypedef np.int_t    INT_t
      ctypedef np.float_t  FLOAT_t
      ctypedef np.double_t DOUBLE_t
      ctypedef np.long_t   LONG_t
               ^
      ------------------------------------------------------------
      
      plastid/genomics/map_factories.pyx:154:9: 'long_t' is not a type identifier
      warning: plastid/genomics/map_factories.pyx:542:24: Index should be typed for more efficient access
      Compiling /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx because it changed.
      [1/1] Cythonizing /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx
      Traceback (most recent call last):
        File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 476, in <module>
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 398, in run
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for plastid
Failed to build plastid
ERROR: Could not build wheels for plastid, which is required to install pyproject.toml-based projects
```

Alternatively is there a way to be able to import plastid in  the python interpreter running in the anaconda environment (where installation succeeded) ?

**Comment by makc-sel** [comment]
> I am trying to install this package locally from source using any of
> 
> ```python
> pip install --user .
> pip install --user -e .
> pip install --user --global-option="--recythonize" .  # since --install-option was removed by pip
> ```
> 
> but I always get the following error
> 
> ```
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting scipy>=0.15.1 (from plastid==0.6.1)
>   Using cached scipy-1.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
> Collecting pandas>=0.17.0 (from plastid==0.6.1)
>   Using cached pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
> Requirement already satisfied: matplotlib>=1.4.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (3.7.2)
> Collecting biopython>=1.64 (from plastid==0.6.1)
>   Using cached biopython-1.81-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
> Collecting twobitreader>=3.0.0 (from plastid==0.6.1)
>   Using cached twobitreader-3.1.7-py3-none-any.whl
> Collecting termcolor (from plastid==0.6.1)
>   Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
> Requirement already satisfied: numpy>=1.9.4 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (1.23.5)
> Requirement already satisfied: pysam>=0.8.4 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (0.21.0)
> Requirement already satisfied: cython>=0.22.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from plastid==0.6.1) (3.0.0)
> Requirement already satisfied: contourpy>=1.0.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (1.1.0)
> Requirement already satisfied: cycler>=0.10 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (0.11.0)
> Requirement already satisfied: fonttools>=4.22.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (4.41.1)
> Requirement already satisfied: kiwisolver>=1.0.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (1.4.4)
> Requirement already satisfied: packaging>=20.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (23.1)
> Requirement already satisfied: pillow>=6.2.0 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (9.5.0)
> Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (3.0.9)
> Requirement already satisfied: python-dateutil>=2.7 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from matplotlib>=1.4.0->plastid==0.6.1) (2.8.2)
> Requirement already satisfied: pytz>=2020.1 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from pandas>=0.17.0->plastid==0.6.1) (2023.3)
> Collecting tzdata>=2022.1 (from pandas>=0.17.0->plastid==0.6.1)
>   Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
> Requirement already satisfied: six>=1.5 in /home/moritzloewer/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->plastid==0.6.1) (1.16.0)
> Building wheels for collected packages: plastid
>   Building wheel for plastid (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for plastid (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [89 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       copying plastid/genomics/roitools.pyx -> build/lib.linux-x86_64-cpython-310/plastid/genomics
>       copying plastid/genomics/map_factories.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
>       copying plastid/genomics/roitools.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
>       copying plastid/genomics/c_common.c -> build/lib.linux-x86_64-cpython-310/plastid/genomics
>       copying plastid/readers/bigwig.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
>       copying plastid/readers/bbifile.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
>       copying plastid/readers/bigbed.c -> build/lib.linux-x86_64-cpython-310/plastid/readers
>       running build_ext
>       building 'plastid.genomics.c_common' extension
>       gcc -pthread -B /home/moritzloewer/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/moritzloewer/anaconda3/include -fPIC -O2 -isystem /home/moritzloewer/anaconda3/include -fPIC -I/home/moritzloewer/Bachelor/plastid/plastid/kent/src/htslib -I/home/moritzloewer/Bachelor/plastid/plastid/kent/src/inc -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/numpy/core/include -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam/include/htslib -I/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/pysam/include/samtools -I/home/moritzloewer/anaconda3/include/python3.10 -c /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.c -o build/temp.linux-x86_64-cpython-310/home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.o
>       gcc -pthread -B /home/moritzloewer/anaconda3/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/moritzloewer/anaconda3/lib -Wl,-rpath-link,/home/moritzloewer/anaconda3/lib -L/home/moritzloewer/anaconda3/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/moritzloewer/anaconda3/lib -Wl,-rpath-link,/home/moritzloewer/anaconda3/lib -L/home/moritzloewer/anaconda3/lib build/temp.linux-x86_64-cpython-310/home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/c_common.o -lssl -lcrypto -lz -o build/lib.linux-x86_64-cpython-310/plastid/genomics/c_common.cpython-310-x86_64-linux-gnu.so
>       warning: plastid/genomics/map_factories.pyx:134:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
>       warning: plastid/genomics/map_factories.pyx:145:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
>       
>       Error compiling Cython file:
>       ------------------------------------------------------------
>       ...
>       LONG   = np.long
>       
>       ctypedef np.int_t    INT_t
>       ctypedef np.float_t  FLOAT_t
>       ctypedef np.double_t DOUBLE_t
>       ctypedef np.long_t   LONG_t
>                ^
>       ------------------------------------------------------------
>       
>       plastid/genomics/map_factories.pyx:154:9: 'long_t' is not a type identifier
>       warning: plastid/genomics/map_factories.pyx:542:24: Index should be typed for more efficient access
>       Compiling /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx because it changed.
>       [1/1] Cythonizing /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx
>       Traceback (most recent call last):
>         File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/home/moritzloewer/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
>           return _build_backend().build_wheel(wheel_directory, config_settings,
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
>           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
>           self.run_setup()
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
>           exec(code, locals())
>         File "<string>", line 476, in <module>
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
>           return distutils.core.setup(**attrs)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
>           return run_commands(dist)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>           dist.run_commands()
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-build-env-i6xqx771/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 346, in run
>           self.run_command("build")
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "<string>", line 398, in run
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
>           self.build_extensions()
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
>           self._build_extensions_serial()
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
>           self.build_extension(ext)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
>           new_ext = cythonize(
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
>           cythonize_one(*args)
>         File "/tmp/pip-build-env-i6xqx771/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
>           raise CompileError(None, pyx_file)
>       Cython.Compiler.Errors.CompileError: /home/moritzloewer/Bachelor/plastid/plastid/plastid/genomics/map_factories.pyx
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for plastid
> Failed to build plastid
> ERROR: Could not build wheels for plastid, which is required to install pyproject.toml-based projects
> ```
> 
> Alternatively is there a way to be able to import plastid in the python interpreter running in the anaconda environment (where installation succeeded) ?

I had the same problem in Python3.10.
I solved it by installing Python 3.8 which required packages, after which I did the following:

git clone https://github.com/joshuagryphon/plastid.git
cd plastid
python3.8 setup.py build_ext --recythonize --inplace
python3.8 -c "from plastid import *"

last command works only in plastid folder
Then I installed the missing packages. Sorry, didn't write them down.
